# Data parameters
data:
  seed: 777
  data_path: '~/.pytorch/EMNIST_data/'
  download: True
  batch_size: 32
  shuffle: True
  drop_last: True
  download: True
  num_workers: 4
  img_size: [28, 28]

# Model parameters
model:
  num_class: 365
  num_block: 7
  dim_channel: 128
  mul_factor: 2
  dropout: 0.5

# Training parameters
train:
  epochs: 100
  lr: 0.001
  betas: [0.9, 0.999]
  eps: 0.00000001
  weight_decay: 0.01

# Save
save:
  model_name: 'celebA'

# Other parameters
others:
  log_period: 50